name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Repo klonlanıyor
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Gerekli paketler kuruluyor
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Uygulama testleri çalıştırılıyor
      run: |
        pytest tests/

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()

    steps:
    - name: Repo klonlanıyor
      uses: actions/checkout@v3

    - name: PythonAnywhere Deploy
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        pip install --upgrade pip
        pip install pythonanywhere
        echo "Deploying to PythonAnywhere..."

        python -m pythonanywhere.deploy \
          --username $PA_USERNAME \
          --api_token $PA_API_TOKEN \
          --site $PA_USERNAME.pythonanywhere.com \
          --source-dir $GITHUB_WORKSPACE \
          --nuke
